import sgMail from '@sendgrid/mail';

if (process.env.SENDGRID_API_KEY) {
    sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export interface EmailData {
    candidateName: string;
    candidateEmail?: string;
    matchedJobs: Array<{
        jobTitle: string;
        score: number;
        reasons: string[];
    }>;
    cvFileName: string;
}

export class EmailService {
    static async sendMatchNotification(emailData: EmailData, cvBuffer: Buffer, cvFileName: string) {
        const emailTo = process.env.EMAIL_TO || 'samerweb3@yahoo.com';

        const msg = {
            to: emailTo,
            from: process.env.EMAIL_FROM || 'noreply@evernurse.ae',
            subject: `New CV Match: ${emailData.candidateName}`,
            html: this.generateEmailTemplate(emailData),
            attachments: [
                {
                    content: cvBuffer.toString('base64'),
                    filename: cvFileName,
                    type: 'application/pdf',
                    disposition: 'attachment'
                }
            ]
        };

        try {
            await sgMail.send(msg);
            console.log('Match notification email sent successfully');
        } catch (error) {
            console.error('Error sending email:', error);
            throw new Error('Failed to send email notification');
        }
    }

    private static generateEmailTemplate(data: EmailData): string {
        return `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: linear-gradient(135deg, #1e40af, #3b82f6); color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .match { background: #f0f9ff; border-left: 4px solid #3b82f6; padding: 15px; margin: 10px 0; }
        .score { font-size: 1.2em; font-weight: bold; color: #059669; }
        .reasons { margin-top: 10px; }
        .footer { background: #f8fafc; padding: 15px; text-align: center; font-size: 0.9em; color: #64748b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>EverNurse CV Matching System</h1>
        <p>New Candidate Match Found</p>
    </div>
    
    <div class="content">
        <h2>Candidate Details</h2>
        <p><strong>Name:</strong> ${data.candidateName}</p>
        ${data.candidateEmail ? `<p><strong>Email:</strong> ${data.candidateEmail}</p>` : ''}
        
        <h2>Matched Positions</h2>
        ${data.matchedJobs.map(job => `
            <div class="match">
                <h3>${job.jobTitle}</h3>
                <p class="score">Match Score: ${job.score}%</p>
                <div class="reasons">
                    <strong>Key Matches:</strong>
                    <ul>
                        ${job.reasons.map(reason => `<li>${reason}</li>`).join('')}
                    </ul>
                </div>
            </div>
        `).join('')}
        
        <p><em>The original CV has been attached to this email for your review.</em></p>
    </div>
    
    <div class="footer">
        <p>This email was automatically generated by the EverNurse CV Matching System</p>
        <p>© 2024 EverNurse. All rights reserved.</p>
    </div>
</body>
</html>
    `;
    }
}